# Generated by Django 2.1.15 on 2021-11-18 01:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False, verbose_name='Inativo?')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.AutorObra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.CategoriaObra')),
            ],
        ),
    ]
