# Generated by Django 2.1.15 on 2021-11-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorobra',
            name='delete_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo?'),
        ),
        migrations.AlterField(
            model_name='categoriaobra',
            name='delete_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo?'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='delete_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo?'),
        ),
    ]
