# Generated by Django 2.1.15 on 2021-11-18 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo?')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo?')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
    ]
