# Generated by Django 2.1.15 on 2021-11-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tipousuario_nik_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipousuario',
            name='nik_name',
        ),
    ]
