# Generated by Django 2.1.15 on 2021-11-18 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_tipousuario_nik_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Inativo?')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('ra_gr', models.CharField(help_text='Informe o RA (para alunos) ou o RG (para professor)', max_length=50, verbose_name='RA / RG')),
                ('serie', models.CharField(max_length=50, verbose_name='Série')),
                ('tel', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Periodo')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.TipoUsuario')),
            ],
        ),
    ]
