# Generated by Django 2.1.15 on 2021-11-18 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delete_flag', models.BooleanField(default=False, verbose_name='Inativo?')),
                ('observation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.Obra')),
            ],
        ),
    ]
