# Generated by Django 2.1.15 on 2021-11-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0009_auto_20211118_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_emprestimo',
        ),
    ]
