# Generated by Django 2.1.15 on 2021-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0010_auto_20211118_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='observation2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição2'),
        ),
    ]
