# Generated by Django 2.1.15 on 2021-11-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios'),
        ('emprestimos', '0012_remove_emprestimos_observation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.Usuarios', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acervo.Obra', verbose_name='Item do acervo'),
        ),
    ]
