# Generated by Django 2.1.15 on 2021-11-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0013_auto_20211118_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
